### ISSUE TITLE
No hero icon for Ana

### ISSUE THREAD

**Issue by danielmarquard** [critcola/discourse-overwatch-hero-icons#2]
There is no hero icon for Ana! I'm aware of this.

The font is incomplete, but I've reached out to @dcmjs, the guy who designed the icons for it, to see about getting Ana's icon added. From there, I hope that @255kb, the guy who developed the font from the icons, will add her icon to the font so that it can be included in this plugin.

**Comment by 255kb** [comment]
I will surely add it to the font as soon as it is available. Let me know. 
☺️

**Comment by dcmjs** [comment]
On it! Give me a few days and I'll upload/post here and to reddit.

**Comment by danielmarquard** [comment]
Any update on the Ana icon, @dcmjs? :)

**Comment by danielmarquard** [comment]
We finally have the icons to complete your font. Thank you to @critcola's co-leader, [Polygonine](http://polygonine.com), for designing the icons for Ana and Sombra!

@256kb, could you please include these in your font?

[ana-sombra-icons.zip](https://github.com/critcola/discourse-overwatch-hero-icons/files/598235/ana-sombra-icons.zip)

**Comment by danielmarquard** [comment]
Hey, @256kb. Let me know if you need anything more from us to implement these new icons in the font. 👍

**Comment by 255kb** [comment]
hey, sorry for the delay. 
Thanks for the work. But while I am ok with the ana icon, it seems that you based Sombra's icon on her ultimate, the skull, rather than the first icon, her head (see the [official page](https://playoverwatch.com/fr-fr/heroes/sombra/). 
Is it on purpose? I think that like for other characters the icon should represent her/him rather than a specific skill. What do you think?

**Comment by Polygonine** [comment]
Hey @255kb sorry about the game of broken telephone here since I don't frequent the site. Here are the files in question to help you with your Sombra problem. 
[sombra2.zip](https://github.com/critcola/discourse-overwatch-hero-icons/files/628681/sombra2.zip)

The main reason I initially chose to do the icon rather than an outline of her face was due to the idea of her identity. She herself used this as her own internet identity and is represented in some of the skins she has for her character. I understand it might stand out so I decided to just whip up the other option for you as well. Hope the project goes well.

**Comment by 255kb** [comment]
Hi @Polygonine, thanks for the new file
I just published a new version of the font ([1.1.0](https://github.com/255kb/overwatch-heroes-icon-font/releases/tag/1.1.0)) with Ana and Sombra icons. For Sombra I finally added both icons so the user can choose 😄 

cheers

**Comment by danielmarquard** [comment]
Fantastic! The new icons are looking great on [Crit Cola's Discourse](https://critcola.com/community/t/new-overwatch-hero-emoji-icons/153/11). @Polygonine, thank you for the vector art, and thank you for updating the font, @255kb!

We'll do this all over again once Doomfist is released. 😉
